[package]
name = "Advent-of-Code-2015"
version = "0.1.0"
authors = ["idem.est"]
description = "Solutions to the 2015 Advent of Code"
license = "Unlicense"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
