[package]
name = "Advent-of-Code-2015"
version = "0.1.0"
authors = ["idem.est"]
description = "Solutions to the 2015 Advent of Code"
license = "Unlicense"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
md5 = "0.7.0"
regex = "1.11.1"
wasm-bindgen = "0.2.100"
